// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'goods_carrier';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String SPLASH_SCREEN_LOGO = 'assets/images/splash_screen_logo.png';
  static const String IC_RADIO_SELECTED = 'assets/svg/ic_radio_selected.svg';
  static const String IC_RADIO_UNSELECTED = 'assets/svg/ic_radio_unselected.svg';
  static const String IC_ROLE_CUSTOMER = 'assets/svg/ic_role_customer.svg';
  static const String IC_ROLE_DRIVER = 'assets/svg/ic_role_driver.svg';
}
