// Generated by tool/generate_res.dart — do not edit by hand.
// Re-run: dart run tool/generate_res.dart
//
// Prefer typed assets: lib/generated/assets.dart

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'goods_carrier';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String IMAGES_APP_ICON = 'assets/images/app_icon.png';
  static const String IMAGES_APP_LOGO = 'assets/images/app_logo.png';
  static const String IMAGES_EMPTY_TRIP_PLACEHOLDER = 'assets/images/empty_trip_placeholder.png';
  static const String IMAGES_LOGIN_SCREEN_BANNER = 'assets/images/login_screen_banner.png';
  static const String IMAGES_SPLASH_SCREEN_LOGO = 'assets/images/splash_screen_logo.png';
  static const String SVG_APP_ICON = 'assets/svg/app_icon.svg';
  static const String SVG_CTA_RIGHT_ARROW = 'assets/svg/cta_right_arrow.svg';
  static const String SVG_IC_OTP_LOCK = 'assets/svg/ic_otp_lock.svg';
  static const String SVG_IC_PROFILE_CAMERA = 'assets/svg/ic_profile_camera.svg';
  static const String SVG_IC_RADIO_SELECTED = 'assets/svg/ic_radio_selected.svg';
  static const String SVG_IC_RADIO_UNSELECTED = 'assets/svg/ic_radio_unselected.svg';
  static const String SVG_IC_ROLE_CUSTOMER = 'assets/svg/ic_role_customer.svg';
  static const String SVG_IC_ROLE_DRIVER = 'assets/svg/ic_role_driver.svg';
  static const String SVG_IC_ROUTE_INFO = 'assets/svg/ic_route_info.svg';
  static const String SVG_IC_SECURE_PAYMENT = 'assets/svg/ic_secure_payment.svg';
  static const String SVG_IC_VERIFIED_CARRIERS = 'assets/svg/ic_verified_carriers.svg';
  static const String SVG_IC_WHATSAPP = 'assets/svg/ic_whatsapp.svg';
}
