// Generated by tool/generate_res.dart — do not edit by hand.
// Re-run: dart run tool/generate_res.dart

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class DefaultRes {
  DefaultRes._();

  static const String PROJECT_NAME = 'goods_carrier';
  static const String PROJECT_VERSION = '1.0.0+1';
  /// Root env file (also listed under flutter.assets).
  static const String ENV_FILE = '.env';
}
