// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'goods_carrier';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String MANROPE_BOLD = 'Manrope-Bold';
  static const String MANROPE_EXTRABOLD = 'Manrope-ExtraBold';
  static const String MANROPE_EXTRALIGHT = 'Manrope-ExtraLight';
  static const String MANROPE_LIGHT = 'Manrope-Light';
  static const String MANROPE_MEDIUM = 'Manrope-Medium';
  static const String MANROPE_REGULAR = 'Manrope-Regular';
  static const String MANROPE_SEMIBOLD = 'Manrope-SemiBold';
}
