// If iFlutter overwrote lib/res/assets_res.dart with duplicate constants,
// regenerate the correct file. Safe to run anytime.
//
//   dart run tool/fix_assets_res_if_broken.dart

import 'dart:io';

void main() {
  final file = File('lib/res/assets_res.dart');
  if (!file.existsSync()) {
    stdout.writeln('assets_res.dart missing — regenerating…');
    _regenerate();
    return;
  }

  final source = file.readAsStringSync();
  final names = RegExp(r'static const String (\w+) =')
      .allMatches(source)
      .map((m) => m.group(1)!)
      .toList();
  final seen = <String>{};
  final duplicates = <String>[];
  for (final name in names) {
    if (!seen.add(name)) duplicates.add(name);
  }

  final looksLikeIFlutter = source.contains('generated by the iFlutter') ||
      source.contains('Generated file. Do not edit.\n// This file is generated by the iFlutter');
  final missingPathPrefix = !source.contains('IMAGES_') && source.contains('APP_ICON');

  if (duplicates.isEmpty && !looksLikeIFlutter && !missingPathPrefix) {
    stdout.writeln('assets_res.dart looks OK.');
    return;
  }

  if (duplicates.isNotEmpty) {
    stdout.writeln(
      'Broken assets_res.dart (duplicate: ${duplicates.toSet().join(', ')}). Regenerating…',
    );
  } else if (looksLikeIFlutter) {
    stdout.writeln('iFlutter assets_res.dart detected. Regenerating…');
  } else {
    stdout.writeln('assets_res.dart missing path-prefixed names. Regenerating…');
  }
  _regenerate();
}

void _regenerate() {
  final result = Process.runSync(
    'dart',
    ['run', 'tool/generate_res.dart'],
    workingDirectory: Directory.current.path,
  );
  stdout.write(result.stdout);
  stderr.write(result.stderr);
  if (result.exitCode != 0) {
    exit(result.exitCode);
  }
}
