// Generates lib/res/assets_res.dart, default_res.dart, and font_res.dart.
//
// Run from project root after adding assets or when iFlutter overwrites these files:
//   dart run tool/generate_res.dart
//
// iFlutter cannot handle duplicate basenames (app_icon.png + app_icon.svg) or
// dotfiles like `.env` — this script uses full paths for unique constant names.

import 'dart:io';

void main() {
  final root = Directory.current;
  if (!File('${root.path}/pubspec.yaml').existsSync()) {
    stderr.writeln('Run from the project root (goods_carrier/).');
    exitCode = 1;
    return;
  }

  final pubspec = File('pubspec.yaml').readAsStringSync();
  final projectName = _readPubspecField(pubspec, 'name') ?? 'goods_carrier';
  final projectVersion = _readPubspecField(pubspec, 'version') ?? '1.0.0';

  final assetPaths = _collectAssetPaths(pubspec, root);
  final fontFamilies = _collectFontFamilies(pubspec);

  _writeAssetsRes(projectName, projectVersion, assetPaths);
  _writeDefaultRes(projectName, projectVersion);
  _writeFontRes(projectName, projectVersion, fontFamilies);

  stdout.writeln(
    'Generated lib/res/assets_res.dart (${assetPaths.length} assets), '
    'default_res.dart, font_res.dart',
  );
}

String? _readPubspecField(String pubspec, String field) {
  final match = RegExp('^$field:\\s*(.+)\$', multiLine: true).firstMatch(pubspec);
  return match?.group(1)?.trim().replaceAll("'", '').replaceAll('"', '');
}

List<String> _collectAssetPaths(String pubspec, Directory root) {
  final paths = <String>{};

  final assetsBlock = RegExp(
    r'flutter:\s*[\s\S]*?assets:\s*([\s\S]*?)(?=\n\s{2}\w|\nfonts:|\Z)',
  ).firstMatch(pubspec);
  if (assetsBlock != null) {
    for (final line in assetsBlock.group(1)!.split('\n')) {
      final trimmed = line.trim();
      if (!trimmed.startsWith('- ')) continue;
      var entry = trimmed.substring(2).trim();
      if (entry.startsWith("'") || entry.startsWith('"')) {
        entry = entry.substring(1, entry.length - 1);
      }
      if (entry.endsWith('/')) {
        final dir = Directory(entry);
        if (dir.existsSync()) {
          for (final entity in dir.listSync(recursive: true)) {
            if (entity is File && !_isHiddenAsset(entity.path)) {
              paths.add(entity.path.replaceAll('\\', '/'));
            }
          }
        }
      } else if (File(entry).existsSync()) {
        paths.add(entry.replaceAll('\\', '/'));
      }
    }
  }

  return paths.toList()..sort();
}

bool _isHiddenAsset(String path) {
  final name = path.split('/').last;
  return name.startsWith('.') || name == '.DS_Store';
}

List<String> _collectFontFamilies(String pubspec) {
  final families = <String>[];
  // pubspec: `    - family: Manrope-Bold` (only top-level family entries).
  for (final match in RegExp(r'-\s*family:\s*([^\n#]+)').allMatches(pubspec)) {
    var family = match.group(1)!.trim();
    if (family.startsWith("'") || family.startsWith('"')) {
      family = family.substring(1, family.length - 1);
    }
    if (family.isNotEmpty && !families.contains(family)) {
      families.add(family);
    }
  }
  return families;
}

/// iFlutter-style name: `Manrope-Bold` → `MANROPE_BOLD`.
String _constNameForFont(String family) {
  return family.replaceAll('-', '_').toUpperCase();
}

/// Unique SCREAMING_SNAKE from full asset path, e.g. `images/app_icon.png` → `IMAGES_APP_ICON`.
String _constNameForAsset(String path) {
  var p = path.replaceAll('\\', '/');
  if (p.startsWith('assets/')) {
    p = p.substring('assets/'.length);
  }
  final dot = p.lastIndexOf('.');
  final withoutExt = dot > 0 ? p.substring(0, dot) : p;
  return withoutExt
      .replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_')
      .replaceAll(RegExp(r'_+'), '_')
      .replaceAll(RegExp(r'^_|_$'), '')
      .toUpperCase();
}

void _writeAssetsRes(
  String projectName,
  String projectVersion,
  List<String> assetPaths,
) {
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_res.dart — do not edit by hand.')
    ..writeln('// Re-run: dart run tool/generate_res.dart')
    ..writeln('//')
    ..writeln('// Prefer typed assets: lib/generated/assets.dart')
    ..writeln()
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln('class AssetsRes {')
    ..writeln('  AssetsRes._();')
    ..writeln()
    ..writeln("  static const String PROJECT_NAME = '$projectName';")
    ..writeln("  static const String PROJECT_VERSION = '$projectVersion';");

  final usedNames = <String>{};
  for (final path in assetPaths) {
    if (path == '.env') continue;
    var name = _constNameForAsset(path);
    if (usedNames.contains(name)) {
      final ext = path.contains('.') ? path.split('.').last.toUpperCase() : '';
      name = ext.isEmpty ? '${name}_ASSET' : '${name}_$ext';
      var i = 2;
      while (usedNames.contains(name)) {
        name = '${name}_$i';
        i++;
      }
    }
    usedNames.add(name);
    buffer.writeln("  static const String $name = '$path';");
  }

  buffer.writeln('}');
  File('lib/res/assets_res.dart').writeAsStringSync(buffer.toString());
}

void _writeDefaultRes(String projectName, String projectVersion) {
  File('lib/res/default_res.dart').writeAsStringSync('''
// Generated by tool/generate_res.dart — do not edit by hand.
// Re-run: dart run tool/generate_res.dart

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class DefaultRes {
  DefaultRes._();

  static const String PROJECT_NAME = '$projectName';
  static const String PROJECT_VERSION = '$projectVersion';
  /// Root env file (also listed under flutter.assets).
  static const String ENV_FILE = '.env';
}
''');
}

void _writeFontRes(
  String projectName,
  String projectVersion,
  List<String> fontFamilies,
) {
  if (fontFamilies.isEmpty) {
    return;
  }

  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_res.dart — do not edit by hand.')
    ..writeln('// Re-run: dart run tool/generate_res.dart')
    ..writeln()
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln('class FontRes {')
    ..writeln('  FontRes._();')
    ..writeln()
    ..writeln("  static const String PROJECT_NAME = '$projectName';")
    ..writeln("  static const String PROJECT_VERSION = '$projectVersion';");

  for (final family in fontFamilies) {
    final name = _constNameForFont(family);
    buffer.writeln("  static const String $name = '$family';");
  }

  buffer.writeln('}');
  File('lib/res/font_res.dart').writeAsStringSync(buffer.toString());
}
