// Syncs root `.env` → iOS Secrets.xcconfig and android/local.properties.
//
// Usage from project root:
//   dart run tool/sync_env.dart

import 'dart:io';

void main() {
  final root = Directory.current;
  if (!File('${root.path}/pubspec.yaml').existsSync()) {
    stderr.writeln('Run from the project root (goods_carrier/).');
    exitCode = 1;
    return;
  }

  final envFile = File('.env');
  if (!envFile.existsSync()) {
    stderr.writeln('Missing .env — run: cp .env.example .env');
    exitCode = 1;
    return;
  }

  final env = _parseDotEnv(envFile.readAsStringSync());
  final apiKey = env['GOOGLE_API_KEY'] ?? '';

  if (apiKey.isEmpty) {
    stderr.writeln('.env must set GOOGLE_API_KEY');
    exitCode = 1;
    return;
  }

  _writeIosSecrets(apiKey);
  _mergeAndroidLocalProperties(apiKey);
  stdout.writeln('Synced .env → ios/Flutter/Secrets.xcconfig & android/local.properties');
}

Map<String, String> _parseDotEnv(String contents) {
  final map = <String, String>{};
  for (final line in contents.split('\n')) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
    final eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    final key = trimmed.substring(0, eq).trim();
    var value = trimmed.substring(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.substring(1, value.length - 1);
    }
    map[key] = value;
  }
  return map;
}

/// iOS Info.plist / AppDelegate expect this build-setting name.
void _writeIosSecrets(String apiKey) {
  final file = File('ios/Flutter/Secrets.xcconfig');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(
    '// Generated by tool/sync_env.dart — do not edit by hand.\n'
    'GOOGLE_MAPS_API_KEY=$apiKey\n',
  );
}

void _mergeAndroidLocalProperties(String apiKey) {
  final file = File('android/local.properties');
  final lines = file.existsSync() ? file.readAsLinesSync() : <String>[];

  final out = <String>[];
  var wroteKey = false;
  for (final line in lines) {
    if (line.startsWith('GOOGLE_API_KEY=') ||
        line.startsWith('GOOGLE_MAPS_API_KEY=') ||
        line.startsWith('GOOGLE_PLACES_API_KEY=')) {
      out.add('GOOGLE_API_KEY=$apiKey');
      wroteKey = true;
    } else {
      out.add(line);
    }
  }
  if (!wroteKey) {
    out.add('GOOGLE_API_KEY=$apiKey');
  }
  file.writeAsStringSync('${out.join('\n')}\n');
}
